<?php
	$con = mysqli_connect("mysql12.000webhost.com","a1738747_Shri1","Suchitra123","a1738747_UserFin");
	$username = $_POST["username"];
	$age= $_POST["age"];
	$email = $_POST["email"];
	$password = $_POST["password"];	
	$name= $_POST["name"];	
	$position= $_POST["position"];	
	$phone= $_POST["phone"];	
	$experience= $_POST["experience"];	
	$curloc= $_POST["curloc"];	
	$desloc= $_POST["desloc"];	
	$imageuri= $_POST["imageuri"];	
        $com1name = $_POST["com1name"];
        $com1pos = $_POST["com1pos"];
        $com1from = $_POST["com1from"];
        $com1to = $_POST["com1to"];
        $com1resp = $_POST["com1resp"];
        $com2name = $_POST["com2name"];
        $com2pos = $_POST["com2pos"];
        $com2from = $_POST["com2from"];
        $com2to = $_POST["com2to"];
        $com2resp = $_POST["com2resp"];
        $com3name = $_POST["com3name"];
        $com3pos = $_POST["com3pos"];
        $com3from = $_POST["com3from"];
        $com3to = $_POST["com3to"];
        $com3resp = $_POST["com3resp"];
	
$statement = mysqli_prepare($con, "INSERT INTO UserInfo (username, name, password, email, age, phone, position, experience, curloc, desloc, imageuri, com1name, com1pos, com1from, com1to, com1resp, com2name, com2pos, com2from, com2to, com2resp, com3name, com3pos, com3from, com3to, com1resp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
	mysqli_stmt_bind_param($statement, "ssssssssssssssssssssssssss", $username, $name, $password, $email, $age, $phone, $position, $experience, $curloc, $desloc, $imageuri, $com1name, $com1pos, $com1from, $com1to, $com1resp, $com2name, $com2pos, $com2from, $com2to, $com2resp, $com3name, $com3pos, $com3from, $com3to, $com3resp);
	
mysqli_stmt_execute($statement);
	mysqli_stmt_close($statement);
	mysqli_close($con);

  $to = "app@novahro.com";
  $subject = "NEW USER REGISTERED";
  $mail_body = " This is an automated email for your information.\n A new user has been registered to the database.\n\n Following are the users credentials:\n  Name:       $name\n  Email ID: $email\n  Phone Number: $phone\n  Age: $age years\n  Desired Opening: $position\n  Work Experience: $experience\n  Current Work Location: $curloc\n  Desired Work Location: $desloc\n Company 1 details: $com1name\n $com1pos \n$com1from to $com1to\n $com1resp\n\n Company 2 details: $com2name\n $com2pos \n$com2from to $com2to\n $com2resp\n\n Company 3 details: $com3name\n $com3pos \n$com3from to $com3to\n $com3resp\n\nAuto Generated by Nova App";
$headers  = "From:DONOTREPLY@NovaHRO.com\n";
$headers .= "Content-type: text\n";
mail($to, $subject, $mail_body, $headers);
?>